<?php

return [
    'countries' => [
        'AF' => 'Afghanistan',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brazil',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'CV' => 'Cabo Verde',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CR' => 'Costa Rica',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'SZ' => 'Eswatini',
        'ET' => 'Ethiopia',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GR' => 'Greece',
        'GD' => 'Grenada',
        'GT' => 'Guatemala',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HN' => 'Honduras',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'North Korea',
        'KR' => 'South Korea',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'MK' => 'North Macedonia',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'QA' => 'Qatar',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican City',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ],
    
    'phone_codes' => [
        '+971' => '+971 (United Arab Emirates)',
        '+1' => '+1 (USA/Canada)',
        '+20' => '+20 (Egypt)',
        '+27' => '+27 (South Africa)',
        '+30' => '+30 (Greece)',
        '+31' => '+31 (Netherlands)',
        '+32' => '+32 (Belgium)',
        '+33' => '+33 (France)',
        '+34' => '+34 (Spain)',
        '+36' => '+36 (Hungary)',
        '+39' => '+39 (Italy)',
        '+40' => '+40 (Romania)',
        '+41' => '+41 (Switzerland)',
        '+43' => '+43 (Austria)',
        '+44' => '+44 (United Kingdom)',
        '+45' => '+45 (Denmark)',
        '+46' => '+46 (Sweden)',
        '+47' => '+47 (Norway)',
        '+48' => '+48 (Poland)',
        '+49' => '+49 (Germany)',
        '+51' => '+51 (Peru)',
        '+52' => '+52 (Mexico)',
        '+53' => '+53 (Cuba)',
        '+54' => '+54 (Argentina)',
        '+55' => '+55 (Brazil)',
        '+56' => '+56 (Chile)',
        '+57' => '+57 (Colombia)',
        '+58' => '+58 (Venezuela)',
        '+60' => '+60 (Malaysia)',
        '+61' => '+61 (Australia)',
        '+62' => '+62 (Indonesia)',
        '+63' => '+63 (Philippines)',
        '+64' => '+64 (New Zealand)',
        '+65' => '+65 (Singapore)',
        '+66' => '+66 (Thailand)',
        '+81' => '+81 (Japan)',
        '+82' => '+82 (South Korea)',
        '+84' => '+84 (Vietnam)',
        '+86' => '+86 (China)',
        '+90' => '+90 (Turkey)',
        '+91' => '+91 (India)',
        '+92' => '+92 (Pakistan)',
        '+93' => '+93 (Afghanistan)',
        '+94' => '+94 (Sri Lanka)',
        '+95' => '+95 (Myanmar)',
        '+98' => '+98 (Iran)',
        '+211' => '+211 (South Sudan)',
        '+212' => '+212 (Morocco)',
        '+213' => '+213 (Algeria)',
        '+216' => '+216 (Tunisia)',
        '+218' => '+218 (Libya)',
        '+220' => '+220 (Gambia)',
        '+221' => '+221 (Senegal)',
        '+222' => '+222 (Mauritania)',
        '+223' => '+223 (Mali)',
        '+224' => '+224 (Guinea)',
        '+225' => '+225 (Ivory Coast)',
        '+226' => '+226 (Burkina Faso)',
        '+227' => '+227 (Niger)',
        '+228' => '+228 (Togo)',
        '+229' => '+229 (Benin)',
        '+230' => '+230 (Mauritius)',
        '+231' => '+231 (Liberia)',
        '+232' => '+232 (Sierra Leone)',
        '+233' => '+233 (Ghana)',
        '+234' => '+234 (Nigeria)',
        '+235' => '+235 (Chad)',
        '+236' => '+236 (Central African Republic)',
        '+237' => '+237 (Cameroon)',
        '+238' => '+238 (Cape Verde)',
        '+239' => '+239 (Sao Tome and Principe)',
        '+240' => '+240 (Equatorial Guinea)',
        '+241' => '+241 (Gabon)',
        '+242' => '+242 (Congo)',
        '+243' => '+243 (DR Congo)',
        '+244' => '+244 (Angola)',
        '+245' => '+245 (Guinea-Bissau)',
        '+246' => '+246 (Diego Garcia)',
        '+248' => '+248 (Seychelles)',
        '+249' => '+249 (Sudan)',
        '+250' => '+250 (Rwanda)',
        '+251' => '+251 (Ethiopia)',
        '+252' => '+252 (Somalia)',
        '+253' => '+253 (Djibouti)',
        '+254' => '+254 (Kenya)',
        '+255' => '+255 (Tanzania)',
        '+256' => '+256 (Uganda)',
        '+257' => '+257 (Burundi)',
        '+258' => '+258 (Mozambique)',
        '+260' => '+260 (Zambia)',
        '+261' => '+261 (Madagascar)',
        '+263' => '+263 (Zimbabwe)',
        '+264' => '+264 (Namibia)',
        '+265' => '+265 (Malawi)',
        '+266' => '+266 (Lesotho)',
        '+267' => '+267 (Botswana)',
        '+268' => '+268 (Eswatini)',
        '+269' => '+269 (Comoros)',
        '+290' => '+290 (Saint Helena)',
        '+291' => '+291 (Eritrea)',
        '+297' => '+297 (Aruba)',
        '+298' => '+298 (Faroe Islands)',
        '+299' => '+299 (Greenland)',
        '+350' => '+350 (Gibraltar)',
        '+351' => '+351 (Portugal)',
        '+352' => '+352 (Luxembourg)',
        '+353' => '+353 (Ireland)',
        '+354' => '+354 (Iceland)',
        '+355' => '+355 (Albania)',
        '+356' => '+356 (Malta)',
        '+357' => '+357 (Cyprus)',
        '+358' => '+358 (Finland)',
        '+359' => '+359 (Bulgaria)',
        '+370' => '+370 (Lithuania)',
        '+371' => '+371 (Latvia)',
        '+372' => '+372 (Estonia)',
        '+373' => '+373 (Moldova)',
        '+374' => '+374 (Armenia)',
        '+375' => '+375 (Belarus)',
        '+376' => '+376 (Andorra)',
        '+377' => '+377 (Monaco)',
        '+378' => '+378 (San Marino)',
        '+379' => '+379 (Vatican City)',
        '+380' => '+380 (Ukraine)',
        '+381' => '+381 (Serbia)',
        '+382' => '+382 (Montenegro)',
        '+385' => '+385 (Croatia)',
        '+386' => '+386 (Slovenia)',
        '+387' => '+387 (Bosnia and Herzegovina)',
        '+389' => '+389 (North Macedonia)',
        '+420' => '+420 (Czech Republic)',
        '+421' => '+421 (Slovakia)',
        '+423' => '+423 (Liechtenstein)',
        '+500' => '+500 (Falkland Islands)',
        '+501' => '+501 (Belize)',
        '+502' => '+502 (Guatemala)',
        '+503' => '+503 (El Salvador)',
        '+504' => '+504 (Honduras)',
        '+505' => '+505 (Nicaragua)',
        '+506' => '+506 (Costa Rica)',
        '+507' => '+507 (Panama)',
        '+508' => '+508 (Saint Pierre and Miquelon)',
        '+509' => '+509 (Haiti)',
        '+590' => '+590 (Guadeloupe)',
        '+591' => '+591 (Bolivia)',
        '+592' => '+592 (Guyana)',
        '+593' => '+593 (Ecuador)',
        '+594' => '+594 (French Guiana)',
        '+595' => '+595 (Paraguay)',
        '+596' => '+596 (Martinique)',
        '+597' => '+597 (Suriname)',
        '+598' => '+598 (Uruguay)',
        '+599' => '+599 (Netherlands Antilles)',
        '+850' => '+850 (North Korea)',
        '+852' => '+852 (Hong Kong)',
        '+853' => '+853 (Macau)',
        '+855' => '+855 (Cambodia)',
        '+856' => '+856 (Laos)',
        '+880' => '+880 (Bangladesh)',
        '+886' => '+886 (Taiwan)',
        '+960' => '+960 (Maldives)',
        '+961' => '+961 (Lebanon)',
        '+962' => '+962 (Jordan)',
        '+963' => '+963 (Syria)',
        '+964' => '+964 (Iraq)',
        '+965' => '+965 (Kuwait)',
        '+966' => '+966 (Saudi Arabia)',
        '+967' => '+967 (Yemen)',
        '+968' => '+968 (Oman)',
        '+970' => '+970 (Palestine)',
        '+972' => '+972 (Israel)',
        '+973' => '+973 (Bahrain)',
        '+974' => '+974 (Qatar)',
        '+975' => '+975 (Bhutan)',
        '+976' => '+976 (Mongolia)',
        '+977' => '+977 (Nepal)',
        '+992' => '+992 (Tajikistan)',
        '+993' => '+993 (Turkmenistan)',
        '+994' => '+994 (Azerbaijan)',
        '+995' => '+995 (Georgia)',
        '+996' => '+996 (Kyrgyzstan)',
        '+998' => '+998 (Uzbekistan)',
    ],
    
    'languages' => [
        'en' => 'English',
        'ar' => 'Arabic',
        'ur' => 'Urdu',
        'hi' => 'Hindi',
        'tl' => 'Tagalog (Filipino)',
        'ml' => 'Malayalam',
        'bn' => 'Bengali',
        'ta' => 'Tamil',
        'te' => 'Telugu',
        'fr' => 'French',
        'es' => 'Spanish',
        'ru' => 'Russian',
        'zh' => 'Chinese (Mandarin)',
        'fa' => 'Persian (Farsi)',
        'de' => 'German',
        'it' => 'Italian',
        'tr' => 'Turkish',
        'ps' => 'Pashto',
        'si' => 'Sinhala',
        'sw' => 'Swahili',
        'pt' => 'Portuguese',
        'ja' => 'Japanese',
        'ko' => 'Korean',
        'id' => 'Indonesian',
        'ms' => 'Malay',
        'vi' => 'Vietnamese',
        'th' => 'Thai',
        'nl' => 'Dutch',
        'el' => 'Greek',
        'pl' => 'Polish',
        'uk' => 'Ukrainian',
        'ro' => 'Romanian',
        'hu' => 'Hungarian',
        'cs' => 'Czech',
        'sv' => 'Swedish',
    ],
    
    'areas' => [
        'Dubai' => [
            'Downtown Dubai',
            'Dubai Marina',
            'Jumeirah Beach Residence (JBR)',
            'Jumeirah',
            'Business Bay',
            'Deira',
            'Bur Dubai',
            'Al Barsha',
            'Dubai Silicon Oasis',
            'Dubai Sports City',
            'Dubai Motor City',
            'Jumeirah Village Circle (JVC)',
            'Jumeirah Lakes Towers (JLT)',
            'Palm Jumeirah',
            'Al Qusais',
            'Al Nahda (Dubai)',
            'Mirdif',
            'International City',
            'Discovery Gardens',
            'Arabian Ranches',
        ],
        'Abu Dhabi' => [
            'Corniche Area',
            'Al Reem Island',
            'Yas Island',
            'Saadiyat Island',
            'Khalifa City',
            'Mohammed Bin Zayed City',
            'Al Raha Beach',
            'Al Khalidiyah',
            'Al Mushrif',
            'Tourist Club Area (TCA)',
        ],
        'Sharjah' => [
            'Al Nahda (Sharjah)',
            'Al Majaz',
            'Al Taawun',
            'Al Qasimia',
            'Muwaileh',
            'Sharjah University City',
            'Al Khan',
        ],
        'Ajman' => [
            'Ajman Downtown',
            'Al Nuaimiya',
            'Al Rashidiya',
            'Al Jurf',
        ],
        'Other Emirates' => [
            'Ras Al Khaimah',
            'Fujairah',
            'Umm Al Quwain',
        ],
        'Other' => [
            'Other Area',
        ]
    ]
];
