<?php

return [

    // Major languages in the UAE
    'ar' => 'Arabic',
    'en' => 'English',
    'hi' => 'Hindi',
    'ur' => 'Urdu',
    'ml' => 'Malayalam',
    'bn' => 'Bengali',
    'tl' => 'Tagalog',
    'ta' => 'Tamil',
    'te' => 'Telugu',
    'fa' => 'Persian',
    'ne' => 'Nepali',
    'si' => 'Sinhala',
    'zh' => 'Chinese',

    // Other major languages - Alphabetical order
    'af' => 'Afrikaans',
    'am' => 'Amharic',
    'hy' => 'Armenian',
    'az' => 'Azerbaijani',
    'eu' => 'Basque',
    'be' => 'Belarusian',
    'bs' => 'Bosnian',
    'bg' => 'Bulgarian',
    'my' => 'Burmese',
    'ca' => 'Catalan',
    'ceb' => 'Cebuano',
    'hr' => 'Croatian',
    'cs' => 'Czech',
    'da' => 'Danish',
    'nl' => 'Dutch',
    'et' => 'Estonian',
    'fi' => 'Finnish',
    'fr' => 'French',
    'ka' => 'Georgian',
    'de' => 'German',
    'el' => 'Greek',
    'gu' => 'Gujarati',
    'ha' => 'Hausa',
    'he' => 'Hebrew',
    'hu' => 'Hungarian',
    'id' => 'Indonesian',
    'ga' => 'Irish',
    'is' => 'Icelandic',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'jv' => 'Javanese',
    'kn' => 'Kannada',
    'kk' => 'Kazakh',
    'km' => 'Khmer',
    'ko' => 'Korean',
    'ku' => 'Kurdish',
    'ky' => 'Kyrgyz',
    'lo' => 'Lao',
    'lv' => 'Latvian',
    'lt' => 'Lithuanian',
    'mk' => 'Macedonian',
    'ms' => 'Malay',
    'mt' => 'Maltese',
    'mr' => 'Marathi',
    'mn' => 'Mongolian',
    'no' => 'Norwegian',
    'or' => 'Odia',
    'ps' => 'Pashto',
    'pl' => 'Polish',
    'pt' => 'Portuguese',
    'pa' => 'Punjabi',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'sr' => 'Serbian',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'so' => 'Somali',
    'es' => 'Spanish',
    'sw' => 'Swahili',
    'sv' => 'Swedish',
    'tg' => 'Tajik',
    'th' => 'Thai',
    'tr' => 'Turkish',
    'tk' => 'Turkmen',
    'uk' => 'Ukrainian',
    'uz' => 'Uzbek',
    'vi' => 'Vietnamese',
    'cy' => 'Welsh',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yi' => 'Yiddish',
    'yo' => 'Yoruba',
    'zu' => 'Zulu',

    // Other
    'other' => 'Other',

];